/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.buffet.view;

import br.com.buffet.dao.AluguelDAO;
import br.com.buffet.model.Aluguel;
import javax.swing.JOptionPane;

/**
 *
 * @author MINEIRO
 */
public class TelaCadastro extends javax.swing.JFrame {
    private Aluguel aluguel;
    private AluguelDAO aluguelDAO;
    
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTelefoneCliente = new javax.swing.JFormattedTextField();
        lbEndereco = new javax.swing.JLabel();
        txtEnderecoFesta = new javax.swing.JTextField();
        txtNomeCliente2 = new javax.swing.JLabel();
        cmbTemaFesta = new javax.swing.JComboBox<>();
        txtNomeCliente3 = new javax.swing.JLabel();
        txtDataFesta = new javax.swing.JFormattedTextField();
        txtNomeCliente4 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JFormattedTextField();
        txtNomeCliente5 = new javax.swing.JLabel();
        txtHoraTermino = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        menuSalvar = new javax.swing.JMenuItem();
        menuAlterar = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenuItem();
        menuExcluir = new javax.swing.JMenuItem();
        jmSobre = new javax.swing.JMenu();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Aluguel do Buffet");

        lbNomeCliente.setText("Nome do Cliente:");

        txtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Telefone do Cliente:");

        try {
            txtTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbEndereco.setText("Endereço da Festa:");

        txtEnderecoFesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoFestaActionPerformed(evt);
            }
        });

        txtNomeCliente2.setText("Tema da Festa:");

        cmbTemaFesta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tema", "Noite Árabe", "Cassino", "Futebol", "Basquete", "Sertanejo" }));

        txtNomeCliente3.setText("Data da Festa:");

        try {
            txtDataFesta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtNomeCliente4.setText("Hora de Início:");

        try {
            txtHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtNomeCliente5.setText("Hora de Término:");

        try {
            txtHoraTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEnderecoFesta))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(368, 368, 368)
                            .addComponent(txtNomeCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHoraTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtNomeCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbTemaFesta, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomeCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtNomeCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHoraInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDataFesta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnderecoFesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTemaFesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jmArquivo.setText("Arquivo");

        menuSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        menuSalvar.setText("Salvar");
        menuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarActionPerformed(evt);
            }
        });
        jmArquivo.add(menuSalvar);

        menuAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_edit.png"))); // NOI18N
        menuAlterar.setText("Alterar");
        menuAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarActionPerformed(evt);
            }
        });
        jmArquivo.add(menuAlterar);

        menuConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_text.png"))); // NOI18N
        menuConsultar.setText("Consultar");
        menuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarActionPerformed(evt);
            }
        });
        jmArquivo.add(menuConsultar);

        menuExcluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_delete.png"))); // NOI18N
        menuExcluir.setText("Excluir");
        menuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirActionPerformed(evt);
            }
        });
        jmArquivo.add(menuExcluir);

        jMenuBar1.add(jmArquivo);

        jmSobre.setText("Sobre");
        jmSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSobre);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteActionPerformed

    private void txtEnderecoFestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoFestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoFestaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        //=================
        try {
            int id;
            id = Integer.parseInt(JOptionPane.showInputDialog("Informe o id do alguel que deseja consultar"));
            aluguel = new Aluguel();
            aluguelDAO = new AluguelDAO();
            aluguel = aluguelDAO.consultar(id);
            txtNomeCliente.setText(aluguel.getNomeCliente());
            txtTelefoneCliente.setText(aluguel.getTelCliente());
            txtEnderecoFesta.setText(aluguel.getEndFesta());      
            switch (aluguel.getTemaFesta()) {
                case "Noite Árabe":
                    cmbTemaFesta.setSelectedIndex(1);
                    break;
                case "Cassino":
                    cmbTemaFesta.setSelectedIndex(2);
                    break;
                case "Futebol":
                    cmbTemaFesta.setSelectedIndex(3);
                    break;
                case "Basquete":
                    cmbTemaFesta.setSelectedIndex(4);
                    break;
                case "Sertanejo":
                    cmbTemaFesta.setSelectedIndex(5);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Não foi possível exibir o tema da festa!");
            }
            txtDataFesta.setText(aluguel.getDtaFesta());
            txtHoraInicio.setText(aluguel.getHoraInicio());
            txtHoraTermino.setText(aluguel.getHoraTermino());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar");
        }    
        //=================
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //=======================
        try {
            // Objeto com os dados da tela
            aluguel = new Aluguel();
            aluguel.setNomeCliente(txtNomeCliente.getText());
            aluguel.setTelCliente(txtTelefoneCliente.getText());
            aluguel.setEndFesta(txtEnderecoFesta.getText());
            if(cmbTemaFesta.getSelectedIndex() == 0) {
                String dao = "Salvar";
                String mot = "Tema";
                maniInvalida(dao, mot);
            } else {
                aluguel.setTemaFesta((String) cmbTemaFesta.getSelectedItem());
            }
            aluguel.setDtaFesta(txtDataFesta.getText());
            aluguel.setHoraInicio(txtHoraInicio.getText());
            aluguel.setHoraTermino(txtHoraTermino.getText());
            // Abre a conexão e salva
            aluguelDAO = new AluguelDAO();
            aluguelDAO.salvar(aluguel);
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            // Após salvar irá limpar os campos
            txtNomeCliente.setText(null);
            txtTelefoneCliente.setText(null);
            txtEnderecoFesta.setText(null);
            cmbTemaFesta.setSelectedIndex(0);
            txtDataFesta.setText(null);
            txtHoraInicio.setText(null);
            txtHoraTermino.setText(null);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar!");
        }    
        //=======================
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        //=======================
        try {
            // Objeto com os dados da tela
            aluguel = new Aluguel();
            aluguel.setNomeCliente(txtNomeCliente.getText());
            aluguel.setTelCliente(txtTelefoneCliente.getText());
            aluguel.setEndFesta(txtEnderecoFesta.getText());
            if(cmbTemaFesta.getSelectedIndex() == 0) {
                String dao = "Alterar";
                String mot = "Tema";
                maniInvalida(dao, mot);
            } else {
                aluguel.setTemaFesta((String) cmbTemaFesta.getSelectedItem());
            }
            aluguel.setDtaFesta(txtDataFesta.getText());
            aluguel.setHoraInicio(txtHoraInicio.getText());
            aluguel.setHoraTermino(txtHoraTermino.getText());
            int id = Integer.parseInt(JOptionPane.showInputDialog("Informe o id do aluguel que deseja alterar"));
            aluguel.setId(id);
            //abre a conexão e altera
            aluguelDAO = new AluguelDAO();
            aluguelDAO.alterar(aluguel);
        } catch(Exception e) {
            /*String dao = "Alterar";
            String mot = e.getMessage();
            maniInvalida(dao, mot); */
            JOptionPane.showMessageDialog(null, "Erro ao alterar!");
        }
        //=======================
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //=======================
        try {
            int id;
            id = Integer.parseInt(JOptionPane.showInputDialog("Informe o id do aluguel que será excluído"));
            // abre a conexão e exclui o dado
            aluguelDAO = new AluguelDAO();
            aluguelDAO.excluir(id);
            JOptionPane.showMessageDialog(null, "Aluguel excluido com sucesso!");
        } catch(Exception e) {
            String dao = "Excluir";
            String mot = "id inexistente";
            maniInvalida(dao, mot);
        }
        //=======================
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        //=======================
        new RelatorioAluguel().setVisible(true);
        this.dispose();
        //=======================
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void menuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarActionPerformed
        //=======================
        try {
            // Objeto com os dados da tela
            aluguel = new Aluguel();
            aluguel.setNomeCliente(txtNomeCliente.getText());
            aluguel.setTelCliente(txtTelefoneCliente.getText());
            aluguel.setEndFesta(txtEnderecoFesta.getText());
            if(cmbTemaFesta.getSelectedIndex() == 0) {
                String dao = "Salvar";
                String mot = "Tema";
                maniInvalida(dao, mot);
            } else {
                aluguel.setTemaFesta((String) cmbTemaFesta.getSelectedItem());
            }
            aluguel.setDtaFesta(txtDataFesta.getText());
            aluguel.setHoraInicio(txtHoraInicio.getText());
            aluguel.setHoraTermino(txtHoraTermino.getText());
            // Abre a conexão e salva
            aluguelDAO = new AluguelDAO();
            aluguelDAO.salvar(aluguel);
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            // Após salvar irá limpar os campos
            txtNomeCliente.setText(null);
            txtTelefoneCliente.setText(null);
            txtEnderecoFesta.setText(null);
            cmbTemaFesta.setSelectedIndex(0);
            txtDataFesta.setText(null);
            txtHoraInicio.setText(null);
            txtHoraTermino.setText(null);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar!");
        }    
        //=======================
    }//GEN-LAST:event_menuSalvarActionPerformed

    private void jmSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSobreMouseClicked
        //===========================
        JOptionPane.showMessageDialog(null, "Sistema desenvolvido por Luiz Felipe para um BUFFET inexistente");
        //===========================
    }//GEN-LAST:event_jmSobreMouseClicked

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        //===========================
        System.exit(0);
        //===========================
    }//GEN-LAST:event_jmSairMouseClicked

    private void menuAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarActionPerformed
        //=======================
        try {
            // Objeto com os dados da tela
            aluguel = new Aluguel();
            aluguel.setNomeCliente(txtNomeCliente.getText());
            aluguel.setTelCliente(txtTelefoneCliente.getText());
            aluguel.setEndFesta(txtEnderecoFesta.getText());
            if(cmbTemaFesta.getSelectedIndex() == 0) {
                String dao = "Alterar";
                String mot = "Tema";
                maniInvalida(dao, mot);
            } else {
                aluguel.setTemaFesta((String) cmbTemaFesta.getSelectedItem());
            }
            aluguel.setDtaFesta(txtDataFesta.getText());
            aluguel.setHoraInicio(txtHoraInicio.getText());
            aluguel.setHoraTermino(txtHoraTermino.getText());
            int id = Integer.parseInt(JOptionPane.showInputDialog("Informe o id do aluguel que deseja alterar"));
            aluguel.setId(id);
            //abre a conexão e altera
            aluguelDAO = new AluguelDAO();
            aluguelDAO.alterar(aluguel);
        } catch(Exception e) {
            /*String dao = "Alterar";
            String mot = e.getMessage();
            maniInvalida(dao, mot); */
            JOptionPane.showMessageDialog(null, "Erro ao alterar!");
        }
        //=======================
    }//GEN-LAST:event_menuAlterarActionPerformed

    private void menuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarActionPerformed
        //=================
        try {
            int id;
            id = Integer.parseInt(JOptionPane.showInputDialog("Informe o id do alguel que deseja consultar"));
            aluguel = new Aluguel();
            aluguelDAO = new AluguelDAO();
            aluguel = aluguelDAO.consultar(id);
            txtNomeCliente.setText(aluguel.getNomeCliente());
            txtTelefoneCliente.setText(aluguel.getTelCliente());
            txtEnderecoFesta.setText(aluguel.getEndFesta());      
            switch (aluguel.getTemaFesta()) {
                case "Noite Árabe":
                    cmbTemaFesta.setSelectedIndex(1);
                    break;
                case "Cassino":
                    cmbTemaFesta.setSelectedIndex(2);
                    break;
                case "Futebol":
                    cmbTemaFesta.setSelectedIndex(3);
                    break;
                case "Basquete":
                    cmbTemaFesta.setSelectedIndex(4);
                    break;
                case "Sertanejo":
                    cmbTemaFesta.setSelectedIndex(5);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Não foi possível exibir o tema da festa!");
            }
            txtDataFesta.setText(aluguel.getDtaFesta());
            txtHoraInicio.setText(aluguel.getHoraInicio());
            txtHoraTermino.setText(aluguel.getHoraTermino());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar");
        }    
        //=================
    }//GEN-LAST:event_menuConsultarActionPerformed

    private void menuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirActionPerformed
        //=======================
        try {
            int id;
            id = Integer.parseInt(JOptionPane.showInputDialog("Informe o id do aluguel que será excluído"));
            // abre a conexão e exclui o dado
            aluguelDAO = new AluguelDAO();
            aluguelDAO.excluir(id);
            JOptionPane.showMessageDialog(null, "Aluguel excluido com sucesso!");
        } catch(Exception e) {
            String dao = "Excluir";
            String mot = "id inexistente";
            maniInvalida(dao, mot);
        }
        //=======================
    }//GEN-LAST:event_menuExcluirActionPerformed
    
    public void maniInvalida(String dao, String motivo) {
        JOptionPane.showMessageDialog(null, "Não foi possível "+ dao +" "+ motivo +" Inválido");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbTemaFesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNomeCliente;
    private javax.swing.JMenuItem menuAlterar;
    private javax.swing.JMenuItem menuConsultar;
    private javax.swing.JMenuItem menuExcluir;
    private javax.swing.JMenuItem menuSalvar;
    private javax.swing.JFormattedTextField txtDataFesta;
    private javax.swing.JTextField txtEnderecoFesta;
    private javax.swing.JFormattedTextField txtHoraInicio;
    private javax.swing.JFormattedTextField txtHoraTermino;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JLabel txtNomeCliente2;
    private javax.swing.JLabel txtNomeCliente3;
    private javax.swing.JLabel txtNomeCliente4;
    private javax.swing.JLabel txtNomeCliente5;
    private javax.swing.JFormattedTextField txtTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
